# Generated by Django 4.2.6 on 2024-05-14 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conta', '0002_alter_usuario_matricula'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='cargo',
            field=models.CharField(default='não identificado', max_length=100),
        ),
        migrations.AddField(
            model_name='usuario',
            name='status',
            field=models.CharField(default='Ativo', max_length=50),
        ),
        migrations.AddField(
            model_name='usuario',
            name='telefone',
            field=models.CharField(default='XXXXXX', max_length=15),
        ),
        migrations.AddField(
            model_name='usuario',
            name='turma',
            field=models.CharField(default='XXXX', max_length=4),
        ),
    ]
