# Generated by Django 4.2.6 on 2024-06-26 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conta', '0006_alter_usuario_telefone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='cargo',
            field=models.CharField(blank=True, default='não identificado', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='status',
            field=models.CharField(blank=True, default='Ativo', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='telefone',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='turma',
            field=models.CharField(blank=True, default='null', max_length=4, null=True),
        ),
    ]
