# Generated by Django 4.2.6 on 2024-07-28 03:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('recursos', '0017_alter_equipamento_imagem_alter_espaco_imagem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataHorarioSolicitacao', models.DateTimeField(auto_now_add=True)),
                ('dataHorarioInicial', models.DateTimeField()),
                ('dataHorarioFinal', models.DateTimeField()),
                ('justificativa', models.CharField(max_length=200)),
                ('andamento', models.CharField(choices=[('em_analise', 'Em Análise'), ('negada', 'Negada'), ('aprovada', 'Aprovada')], default='em_analise', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='ReservaEspaco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('espaco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reserva_espaco', to='recursos.espaco')),
                ('reserva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reserva_espaco', to='reserva.reserva')),
            ],
        ),
        migrations.CreateModel(
            name='ReservaEquipamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataHorarioRetirada', models.DateTimeField(blank=True, null=True)),
                ('dataHorarioDevolucao', models.DateTimeField(blank=True, null=True)),
                ('recurso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reserva_equipamento', to='recursos.equipamento')),
                ('reserva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reserva_equipamento', to='reserva.reserva')),
            ],
        ),
        migrations.AddField(
            model_name='reserva',
            name='equipamentos',
            field=models.ManyToManyField(related_name='reservasequipamento', through='reserva.ReservaEquipamento', to='recursos.equipamento'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='espacos',
            field=models.ManyToManyField(related_name='reservasespaco', through='reserva.ReservaEspaco', to='recursos.espaco'),
        ),
    ]
