# Generated by Django 4.2.6 on 2024-07-28 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recursos', '0018_alter_equipamento_setor_alter_espaco_setor'),
        ('reserva', '0002_reserva_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='equipamentos',
            field=models.ManyToManyField(blank=True, related_name='reservasequipamento', through='reserva.ReservaEquipamento', to='recursos.equipamento'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='espacos',
            field=models.ManyToManyField(blank=True, related_name='reservasespaco', through='reserva.ReservaEspaco', to='recursos.espaco'),
        ),
    ]
