# Generated by Django 4.2.6 on 2024-08-19 01:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0013_alter_usuario_setor'),
        ('reserva', '0003_alter_reserva_equipamentos_alter_reserva_espacos'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='situacao',
            field=models.CharField(default='d', max_length=2),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='usuario.usuario'),
        ),
    ]
