# Generated by Django 4.2.6 on 2024-05-14 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0003_usuario_cargo_usuario_status_usuario_telefone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='telefone',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='turma',
            field=models.CharField(max_length=4),
        ),
    ]
