# Generated by Django 4.2.6 on 2024-07-02 00:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0008_alter_usuario_turma'),
        ('usuario', '0008_usuario_tipo_alter_usuario_turma'),
    ]

    operations = [
    ]
