# Generated by Django 4.2.6 on 2024-07-02 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0009_merge_20240701_2111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='cargo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
