# Generated by Django 4.2.6 on 2024-08-20 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0013_alter_usuario_setor'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='tempo_punicao',
            field=models.DateField(blank=True, null=True),
        ),
    ]
