# Generated by Django 4.2.6 on 2024-08-21 00:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0014_usuario_tempo_punicao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='tempo_punicao',
        ),
    ]
