# Generated by Django 4.2.6 on 2024-02-25 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('imagem', models.ImageField(upload_to='fotos/')),
                ('descrição', models.CharField(max_length=100)),
                ('dataAquisição', models.DateField()),
                ('tipo', models.CharField(choices=[('equipamento', 'Equipamento'), ('espaco', 'Espaço')], max_length=12)),
            ],
        ),
    ]
