# Generated by Django 4.2.6 on 2024-02-25 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recursos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recurso',
            old_name='dataAquisição',
            new_name='dataAquisicao',
        ),
        migrations.RenameField(
            model_name='recurso',
            old_name='descrição',
            new_name='descricao',
        ),
    ]
