# Generated by Django 4.2.6 on 2024-02-25 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recursos', '0002_rename_dataaquisição_recurso_dataaquisicao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recurso',
            name='tipo',
            field=models.CharField(choices=[('Equipamento', 'Equipamento'), ('Espaço', 'Espaço')], max_length=12),
        ),
    ]
