# Generated by Django 4.2.6 on 2024-02-27 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recursos', '0004_alter_recurso_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recurso',
            name='imagem',
            field=models.ImageField(upload_to='pictures/%Y/%m/'),
        ),
    ]
