# Generated by Django 4.2.6 on 2024-02-27 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recursos', '0006_remove_recurso_dataaquisicao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recurso',
            name='imagem',
            field=models.ImageField(blank='true', upload_to='pictures/%Y/%m/'),
        ),
    ]
