# Generated by Django 4.2.6 on 2024-05-13 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recursos', '0007_alter_recurso_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recurso',
            name='descricao',
            field=models.CharField(blank='True', max_length=100, null='True'),
        ),
        migrations.AlterField(
            model_name='recurso',
            name='imagem',
            field=models.ImageField(blank='False', null='False', upload_to='pictures/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='recurso',
            name='nome',
            field=models.CharField(blank='False', max_length=100, null='False'),
        ),
        migrations.AlterField(
            model_name='recurso',
            name='tipo',
            field=models.CharField(blank='False', choices=[('eq', 'Equipamento'), ('es', 'Espaço')], max_length=12, null='False'),
        ),
    ]
