# Generated by Django 4.2.6 on 2024-05-14 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recursos', '0008_alter_recurso_descricao_alter_recurso_imagem_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recurso',
            name='tipo',
            field=models.CharField(blank='False', choices=[('eq', 'Equipamento'), ('Espaço', 'es')], max_length=12, null='False'),
        ),
    ]
