# Generated by Django 4.2.6 on 2024-05-14 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recursos', '0009_alter_recurso_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recurso',
            name='tipo',
            field=models.CharField(blank='False', choices=[('Equipamento', 'Equipamento'), ('Espaco', 'Espaço')], max_length=12, null='False'),
        ),
    ]
