# Generated by Django 4.2.6 on 2024-06-01 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recursos', '0010_alter_recurso_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='recurso',
            name='quantidade',
            field=models.IntegerField(default=1),
        ),
    ]
