# Generated by Django 4.2.6 on 2024-06-05 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recursos', '0012_equipamento_espaco_delete_recurso'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipamento',
            name='quantDisponivel',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
