# Generated by Django 4.2.6 on 2024-07-07 03:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recursos', '0013_equipamento_quantdisponivel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipamento',
            name='quantDisponivel',
        ),
    ]
