# Generated by Django 4.2.6 on 2024-07-26 02:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('setor', '0001_initial'),
        ('recursos', '0014_remove_equipamento_quantdisponivel'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipamento',
            name='setor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='equipamentos', to='setor.setor'),
        ),
        migrations.AddField(
            model_name='espaco',
            name='setor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='espacos', to='setor.setor'),
        ),
    ]
