# Generated by Django 4.2.6 on 2024-07-26 22:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('setor', '0001_initial'),
        ('recursos', '0015_equipamento_setor_espaco_setor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipamento',
            name='imagem',
            field=models.ImageField(blank='True', null='True', upload_to='pictures/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='equipamento',
            name='setor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='equipamentos', to='setor.setor'),
        ),
        migrations.AlterField(
            model_name='espaco',
            name='imagem',
            field=models.ImageField(blank='True', null='True', upload_to='pictures/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='espaco',
            name='setor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='espacos', to='setor.setor'),
        ),
    ]
