# Generated by Django 4.2.6 on 2024-07-27 04:40


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recursos', '0016_alter_equipamento_imagem_alter_equipamento_setor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipamento',
            name='imagem',
            field=models.ImageField(blank='False', null='False', upload_to='pictures/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='espaco',
            name='imagem',
            field=models.ImageField(blank='False', null='False', upload_to='pictures/%Y/%m/'),
        ),
    ]
