# Generated by Django 4.2.6 on 2024-08-19 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recursos', '0018_alter_equipamento_setor_alter_espaco_setor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipamento',
            name='descricao',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='equipamento',
            name='imagem',
            field=models.ImageField(upload_to='pictures/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='equipamento',
            name='nome',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='espaco',
            name='descricao',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='espaco',
            name='imagem',
            field=models.ImageField(upload_to='pictures/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='espaco',
            name='nome',
            field=models.CharField(max_length=100),
        ),
    ]
